jobs:
  ma_compute:
    targets:
      nasdaq-100:
        index_code: NDX
        country: US
        indicators:
          - key: sma
            params:
              window: 50
          - key: sma
            params:
              window: 150
          - key: sma
            params:
              window: 200

  atr_compute:
    targets:
      nasdaq-100:
        index_code: NDX
        country: US
        indicators:
          - key: atr
            params:
              window: 20
